In [9]:
import pandas as pd
import numpy as np
data = {
    'Temperature': ['Hot','Cold','Very Hot', 'Warm', 'Hot', 'Warm', 'Warm', 'Hot', 'Hot','Cold'],
    'Color': ['Red', 'Yellow', 'Blue', 'Blue', 'Red', 'Yellow', 'Red', 'Yellow', 'Yellow', 'Yellow'],
    'Target': [1,1,1,0,1,0,1,0,1,1]
}
df = pd.DataFrame(data,columns = ['Temperature', 'Color', 'Target'])

In [6]:
df = pd.get_dummies(df,prefix=['Temp'], columns = ['Temperature'])
df

    Color  Target  Temp_Cold  Temp_Hot  Temp_Very Hot  Temp_Warm
0     Red       1          0         1              0          0
1  Yellow       1          1         0              0          0
2    Blue       1          0         0              1          0
3    Blue       0          0         0              0          1
4     Red       1          0         1              0          0
5  Yellow       0          0         0              0          1
6     Red       1          0         0              0          1
7  Yellow       0          0         1              0          0
8  Yellow       1          0         1              0          0
9  Yellow       1          1         0              0          0

In [10]:
from sklearn.preprocessing import OneHotEncoder
ohc = OneHotEncoder()
ohe = ohc.fit_transform(df.Temperature.values.reshape(-1,1)).toarray()
dfOneHot = pd.DataFrame(ohe, columns = ["Temp_"+str(ohc.categories_[0][i])
                                       for i in range(len(ohc.categories_[0]))])
dfh = pd.concat([df, dfOneHot], axis=1)
dfh

  Temperature   Color  Target  Temp_Cold  Temp_Hot  Temp_Very Hot  Temp_Warm
0         Hot     Red       1        0.0       1.0            0.0        0.0
1        Cold  Yellow       1        1.0       0.0            0.0        0.0
2    Very Hot    Blue       1        0.0       0.0            1.0        0.0
3        Warm    Blue       0        0.0       0.0            0.0        1.0
4         Hot     Red       1        0.0       1.0            0.0        0.0
5        Warm  Yellow       0        0.0       0.0            0.0        1.0
6        Warm     Red       1        0.0       0.0            0.0        1.0
7         Hot  Yellow       0        0.0       1.0            0.0        0.0
8         Hot  Yellow       1        0.0       1.0            0.0        0.0
9        Cold  Yellow       1        1.0       0.0            0.0        0.0

In [11]:
from sklearn.preprocessing import LabelEncoder
df['Temp_label_encoded'] = LabelEncoder().fit_transform(df.Temperature)
df

  Temperature   Color  Target  Temp_label_encoded
0         Hot     Red       1                   1
1        Cold  Yellow       1                   0
2    Very Hot    Blue       1                   2
3        Warm    Blue       0                   3
4         Hot     Red       1                   1
5        Warm  Yellow       0                   3
6        Warm     Red       1                   3
7         Hot  Yellow       0                   1
8         Hot  Yellow       1                   1
9        Cold  Yellow       1                   0

In [12]:
df.loc[:, 'Temp_factorize_encode'] = pd.factorize(df['Temperature'])[0].reshape(-1,1)
df

  Temperature   Color  Target  Temp_label_encoded  Temp_factorize_encode
0         Hot     Red       1                   1                      0
1        Cold  Yellow       1                   0                      1
2    Very Hot    Blue       1                   2                      2
3        Warm    Blue       0                   3                      3
4         Hot     Red       1                   1                      0
5        Warm  Yellow       0                   3                      3
6        Warm     Red       1                   3                      3
7         Hot  Yellow       0                   1                      0
8         Hot  Yellow       1                   1                      0
9        Cold  Yellow       1                   0                      1

In [13]:
Temp_dict = {
    'Cold' : 1,
    'Warm' : 2,
    'Hot' : 3,
    'Very Hot' : 4
            }
df['Temp_Ordinal'] = df.Temperature.map(Temp_dict)
df

,Temperature,Color,Target,Temp_label_encoded,Temp_factorize_encode,Temp_Ordinal
0,Hot,Red,1,1,0,3
1,Cold,Yellow,1,0,1,1
2,Very Hot,Blue,1,2,2,4
3,Warm,Blue,0,3,3,2
4,Hot,Red,1,1,0,3
5,Warm,Yellow,0,3,3,2
6,Warm,Red,1,3,3,2
7,Hot,Yellow,0,1,0,3
8,Hot,Yellow,1,1,0,3
9,Cold,Yellow,1,0,1,1

In [17]:
import category_encoders as ce
encoder = ce.HelmertEncoder(cols=['Temperature'],drop_invariant=True)
df = pd.concat([df, dfh], axis=1)
df

ModuleNotFoundError: No module named 'category_encoders'